# Generated by Django 5.1.2 on 2024-10-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile-images/user-default.png', null=True, upload_to='profile-images/', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Ustoz'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Superadmin')], default='STUDENT', max_length=10, verbose_name='Role'),
        ),
    ]
