# Generated by Django 5.1.2 on 2024-11-06 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
        ('app_users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_studying',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruhi'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('subject_name', models.CharField(blank=True, max_length=50, verbose_name='Fan nomi')),
                ('teacher_name', models.CharField(blank=True, max_length=100, verbose_name='Ustoz nomi')),
                ('is_started', models.BooleanField(default=False, verbose_name='Boshlanganlik statusi')),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('lecture_days', models.CharField(choices=[('even', 'Dush, Chor, Jum'), ('odd', 'Sesh, Pay, Sha'), ('bootcamp', 'Dush, Sesh, Chor, Pay, Jum')], max_length=26, verbose_name='Dars kunlari')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.teacher', verbose_name='Guruh ustozi')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.group', verbose_name='Guruhi'),
        ),
    ]
