# Generated by Django 5.1.2 on 2024-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_user_options_user_is_studying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_started',
            field=models.BooleanField(default=True, verbose_name='Boshlanganlik statusi'),
        ),
    ]
