# Generated by Django 5.1.2 on 2024-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_group_end_date_alter_group_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
    ]
