# Generated by Django 5.1.2 on 2024-11-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_user_is_studying'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.CharField(max_length=50, null=True, verbose_name='Filial'),
        ),
    ]
