# Generated by Django 5.1.2 on 2024-11-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_group_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='branch',
            field=models.CharField(max_length=50, verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(verbose_name='Tugash sanasi'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.group', verbose_name='Guruh')),
            ],
        ),
    ]
