# Generated by Django 5.1.2 on 2024-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_group_end_date_alter_group_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lecture_days',
            field=models.CharField(choices=[('odd', 'Dush, Chor, Jum'), ('even', 'Sesh, Pay, Sha'), ('bootcamp', 'Dush, Sesh, Chor, Pay, Jum')], max_length=26, verbose_name='Dars kunlari'),
        ),
    ]
