# Generated by Django 5.1.2 on 2024-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_alter_group_lecture_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Dars tugash vaqti'),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Dars boshlanish vaqti'),
        ),
    ]
